import React, { useState, useEffect } from 'react';
import { getMaterials, getSubmissions, addSubmission, getCertBg, getUsers } from '../services/firebase';
import { Student, Material, Submission, Role } from '../types';
import { CheckCircle, Clock, FileText, ChevronLeft, Download, X, Type, Image as ImageIcon, Upload, Trash2, MessageSquare, AlertCircle, PlayCircle, File as FileIcon, Loader2 } from 'lucide-react';

interface Props {
  student: Student;
}

export const StudentReading: React.FC<Props> = ({ student }) => {
  const [materials, setMaterials] = useState<Material[]>([]);
  const [selectedMaterial, setSelectedMaterial] = useState<Material | null>(null);
  const [submissions, setSubmissions] = useState<Submission[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  
  // Form State
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formError, setFormError] = useState('');
  const [submitSuccess, setSubmitSuccess] = useState(false);
  
  // Task State
  const [taskType, setTaskType] = useState<'TEXT' | 'IMAGE'>('TEXT');
  const [taskContent, setTaskContent] = useState<string>('');
  
  const [showCert, setShowCert] = useState(false);
  const [certBg, setCertBg] = useState('');
  const [teacherName, setTeacherName] = useState('');

  useEffect(() => {
    loadData();
  }, [student]);

  const loadData = async () => {
    setIsLoading(true);
    try {
        const mats = await getMaterials(student.grade);
        setMaterials(mats);
        
        const subs = await getSubmissions(student.id);
        setSubmissions(subs);
        
        const bg = await getCertBg();
        setCertBg(bg);

        // Find teacher
        const users = await getUsers();
        const teacher = users.find(u => u.role === Role.TEACHER && u.assignedClass === student.grade);
        setTeacherName(teacher ? teacher.fullName : 'Wali Kelas');
    } catch (e) {
        console.error(e);
    } finally {
        setIsLoading(false);
    }
  };

  // Reset form when material changes
  useEffect(() => {
    if (selectedMaterial) {
        setAnswers({});
        setTaskContent('');
        setTaskType('TEXT');
        setFormError('');
        setSubmitSuccess(false);
    }
  }, [selectedMaterial]);

  const getStatus = (matId: string) => {
    const sub = submissions.find(s => s.materialId === matId);
    return sub ? sub.status : 'NONE';
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormError('');
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 1000000) { // 1MB limit
        setFormError("Ukuran gambar terlalu besar (Maks 1MB).");
        return;
      }
      const reader = new FileReader();
      reader.onloadend = () => {
        setTaskContent(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSubmit = async () => {
    if (!selectedMaterial) return;
    setFormError('');

    // Validation
    const unanswered = selectedMaterial.questions.some(q => !answers[q.id]);
    if (unanswered) {
        setFormError("Harap isi semua jawaban refleksi.");
        return;
    }

    if (selectedMaterial.hasTask && !taskContent) {
        setFormError("Harap kerjakan tugas (Ketik jawaban atau Upload gambar).");
        return;
    }

    setIsSubmitting(true);
    const submission: Submission = {
      id: '', // Generated by firebase
      materialId: selectedMaterial.id,
      studentId: student.id,
      studentName: student.name,
      reflectionAnswers: Object.entries(answers).map(([qid, ans]) => ({ questionId: qid, answer: ans as string })),
      
      // New fields
      taskSubmissionType: selectedMaterial.hasTask ? taskType : undefined,
      taskSubmissionContent: selectedMaterial.hasTask ? taskContent : undefined,
      
      status: 'PENDING',
      submittedAt: new Date().toISOString()
    };

    try {
        await addSubmission(submission);
        await loadData(); // Reload to get new submissions
        setSubmitSuccess(true);
        // Delay closing to show success message
        setTimeout(() => setSelectedMaterial(null), 2000);
    } catch (e) {
        setFormError("Gagal mengirim jawaban. Periksa koneksi internet.");
    } finally {
        setIsSubmitting(false);
    }
  };

  const handlePrintCert = () => {
    const printContent = document.getElementById('certificate-view');
    if (printContent) {
      const win = window.open('', '', 'height=700,width=1000');
      if(win) {
        win.document.write('<html><head><title>Sertifikat Literasi</title>');
        win.document.write('<script src="https://cdn.tailwindcss.com"></script>'); 
        win.document.write('</head><body >');
        win.document.write(printContent.innerHTML);
        win.document.write('</body></html>');
        win.document.close();
        // Allow styles to load
        setTimeout(() => {
            win.print();
        }, 1000);
      }
    }
  };

  // Certificate Component View
  const CertificateView = () => (
    <div id="certificate-view" className="relative w-full aspect-[1.414/1] bg-white text-gray-800 overflow-hidden shadow-2xl">
        {/* Background Layer */}
        {certBg ? (
           <img src={certBg} alt="Background" className="absolute inset-0 w-full h-full object-cover" />
        ) : (
           <div className="absolute inset-0 border-[20px] border-double border-senja-primary/30 m-4"></div>
        )}
        
        {/* Content Layer */}
        <div className="absolute inset-0 flex flex-col items-center justify-center text-center p-12 bg-white/90 md:bg-white/60 backdrop-blur-[1px]">
             <div className="border-4 border-double border-gray-900/20 w-full h-full flex flex-col items-center justify-center p-8 rounded-lg">
                <div className="mb-2 text-center">
                    <h2 className="text-xl md:text-2xl font-bold text-gray-800 tracking-widest uppercase mb-1">SD NEGERI 5 BILATO</h2>
                    <div className="w-full h-0.5 bg-gray-800 mb-2 mx-auto"></div>
                    <h1 className="text-4xl md:text-5xl font-serif font-bold text-senja-dark tracking-wider uppercase mb-1">Sertifikat</h1>
                    <p className="text-lg font-serif italic text-gray-700">Penghargaan Literasi Digital</p>
                </div>

                <div className="w-24 h-1 bg-senja-primary my-4 rounded-full"></div>

                <p className="text-lg text-gray-600 mb-2">Diberikan kepada :</p>
                <h2 className="text-3xl md:text-4xl font-bold text-gray-900 font-serif mb-1">{student.name}</h2>
                <p className="text-lg font-bold text-gray-600 mb-4">Siswa Kelas {student.grade}</p>
                
                <p className="text-gray-700 max-w-2xl leading-relaxed text-sm md:text-base">
                  Telah berhasil membaca, memahami, dan mengerjakan refleksi dengan sangat baik pada materi:
                </p>
                
                {/* JUDUL BACAAN */}
                <h3 className="text-xl md:text-2xl font-bold text-senja-primary font-serif mt-2 mb-6 italic px-4">
                  "{selectedMaterial?.title}"
                </h3>
                
                {/* Tanda Tangan */}
                <div className="mt-auto mb-4 flex justify-between w-full max-w-2xl px-8 md:px-12 items-end">
                   <div className="text-center flex flex-col items-center">
                      {/* QR CODE Wali Kelas */}
                      <img 
                        src={`https://api.qrserver.com/v1/create-qr-code/?size=100x100&data=Disetujui Oleh ${teacherName} - Wali Kelas ${student.grade} - ${student.name} - SD NEGERI 5 BILATO`} 
                        alt="TTD Digital" 
                        className="w-20 h-20 mb-2 mix-blend-multiply"
                      />
                      <p className="font-bold border-t border-gray-500 pt-2 px-4 w-auto min-w-[160px]">{teacherName}</p>
                      <p className="text-xs text-gray-500">Wali Kelas {student.grade}</p>
                   </div>
                   
                   <div className="text-center pb-1">
                      <p className="font-bold border-b border-gray-500 pb-2 px-8 mb-1">{new Date().toLocaleDateString('id-ID', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
                      <p className="text-xs text-gray-500">Tanggal Penyelesaian</p>
                   </div>
                </div>
             </div>
        </div>
    </div>
  );

  if (isLoading) {
      return (
          <div className="flex items-center justify-center min-h-[400px]">
              <Loader2 className="w-12 h-12 animate-spin text-senja-primary" />
          </div>
      )
  }

  if (selectedMaterial) {
    const existingSubmission = submissions.find(s => s.materialId === selectedMaterial.id);

    return (
      <div className="max-w-4xl mx-auto space-y-6 animate-in slide-in-from-right duration-300">
        <button onClick={() => setSelectedMaterial(null)} className="flex items-center text-gray-500 hover:text-senja-primary">
          <ChevronLeft className="w-4 h-4 mr-1" /> Kembali ke Daftar
        </button>

        <div className="bg-white rounded-xl shadow-lg overflow-hidden">
          {selectedMaterial.mediaUrl && selectedMaterial.type === 'image' && (
            <img src={selectedMaterial.mediaUrl} alt={selectedMaterial.title} className="w-full h-64 object-cover" />
          )}
          
          <div className="p-8">
            <h1 className="text-3xl font-bold mb-4">{selectedMaterial.title}</h1>
            
            {/* --- VIDEO PREVIEW --- */}
            {selectedMaterial.type === 'video' && selectedMaterial.linkUrl && (
              <div className="mb-8">
                 <h3 className="font-bold text-gray-800 mb-3 flex items-center gap-2 text-lg">
                    <PlayCircle className="w-6 h-6 text-red-600" /> Video Pembelajaran
                 </h3>
                 {(() => {
                    const getYouTubeId = (url: string) => {
                        const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
                        const match = url.match(regExp);
                        return (match && match[2].length === 11) ? match[2] : null;
                    };
                    const ytId = getYouTubeId(selectedMaterial.linkUrl);

                    if (ytId) {
                        return (
                            <div className="aspect-video w-full rounded-xl overflow-hidden shadow-lg bg-black">
                                <iframe 
                                    className="w-full h-full"
                                    src={`https://www.youtube.com/embed/${ytId}?rel=0&modestbranding=1`}
                                    title="Video Player"
                                    frameBorder="0"
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                    allowFullScreen
                                ></iframe>
                            </div>
                        );
                    } else {
                        return (
                             <div className="bg-black rounded-xl overflow-hidden shadow-lg">
                                 <video controls className="w-full max-h-[500px]">
                                    <source src={selectedMaterial.linkUrl} />
                                    Browser Anda tidak mendukung tag video.
                                 </video>
                             </div>
                        );
                    }
                 })()}
                 <div className="mt-2 text-right">
                    <a href={selectedMaterial.linkUrl} target="_blank" rel="noreferrer" className="text-xs text-blue-500 hover:underline">
                        Jika video tidak muncul, klik di sini
                    </a>
                 </div>
              </div>
            )}

            {/* --- PDF PREVIEW --- */}
            {selectedMaterial.type === 'pdf' && selectedMaterial.linkUrl && (
                <div className="mb-8">
                    <h3 className="font-bold text-gray-800 mb-3 flex items-center gap-2 text-lg">
                        <FileIcon className="w-6 h-6 text-red-500" /> Dokumen Materi (PDF)
                    </h3>
                    <div className="w-full h-[600px] bg-gray-100 rounded-xl overflow-hidden border border-gray-200 shadow-sm relative group">
                        <iframe 
                            src={selectedMaterial.linkUrl.includes('drive.google.com') 
                                ? selectedMaterial.linkUrl.replace('/view', '/preview') 
                                : `https://docs.google.com/gview?url=${encodeURIComponent(selectedMaterial.linkUrl)}&embedded=true`
                            }
                            className="w-full h-full"
                            title="PDF Preview"
                            frameBorder="0"
                        ></iframe>
                        
                        <div className="absolute bottom-0 left-0 right-0 bg-white/90 p-3 text-center border-t backdrop-blur-sm">
                            <a href={selectedMaterial.linkUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-4 py-2 bg-senja-primary text-white rounded-lg text-sm font-bold hover:bg-orange-600 transition shadow-md">
                                <Download className="w-4 h-4" /> Download / Buka Full PDF
                            </a>
                        </div>
                    </div>
                </div>
            )}

            <div className="prose max-w-none text-gray-700 leading-relaxed mb-8 text-lg">
              {selectedMaterial.content}
            </div>

            <hr className="my-8 border-gray-200" />

            {/* Reflection Section */}
            <div className="bg-orange-50 p-6 rounded-xl border border-orange-100">
              <h3 className="text-xl font-bold text-orange-800 mb-4 flex items-center">
                <FileText className="w-5 h-5 mr-2" /> Refleksi & Tugas
              </h3>

              {existingSubmission ? (
                <div className="text-center py-6">
                  {existingSubmission.status === 'APPROVED' ? (
                     <div className="text-green-600 flex flex-col items-center animate-in fade-in zoom-in duration-500">
                       <CheckCircle className="w-16 h-16 mb-2" />
                       <span className="font-bold text-xl mb-1">Hebat! Tugas Disetujui!</span>
                       <p className="text-sm text-gray-600 mb-4">Kamu telah menyelesaikan materi ini dengan baik.</p>
                       
                       {existingSubmission.teacherFeedback && (
                         <div className="bg-white p-4 rounded-xl border border-green-200 shadow-sm max-w-md w-full mb-6 relative">
                            <div className="absolute -top-3 left-1/2 transform -translate-x-1/2 bg-green-100 text-green-800 text-xs font-bold px-3 py-1 rounded-full border border-green-200 flex items-center gap-1">
                                <MessageSquare className="w-3 h-3" /> Catatan Guru
                            </div>
                            <p className="text-gray-700 italic text-sm mt-2">"{existingSubmission.teacherFeedback}"</p>
                         </div>
                       )}

                       <button 
                         onClick={() => setShowCert(true)}
                         className="bg-senja-primary text-white px-8 py-3 rounded-full flex items-center shadow-lg hover:bg-orange-600 animate-bounce transition font-bold"
                       >
                         <Download className="w-5 h-5 mr-2" /> Lihat Sertifikat
                       </button>
                     </div>
                  ) : existingSubmission.status === 'REJECTED' ? (
                      <div className="text-red-600 flex flex-col items-center">
                        <AlertCircle className="w-16 h-16 mb-2" />
                        <span className="font-bold text-xl">Tugas Perlu Perbaikan</span>
                        <p className="text-sm text-gray-600 mb-4">Silakan periksa catatan guru di bawah ini.</p>
                         
                         {existingSubmission.teacherFeedback && (
                             <div className="bg-white p-4 rounded-xl border border-red-200 shadow-sm max-w-md w-full mt-2 text-left">
                                <p className="text-xs font-bold text-red-500 uppercase mb-1">Catatan Guru:</p>
                                <p className="text-gray-800">"{existingSubmission.teacherFeedback}"</p>
                             </div>
                         )}
                         <p className="text-xs text-gray-500 mt-4">Hubungi gurumu untuk mengirim ulang tugas.</p>
                      </div>
                  ) : (
                    <div className="text-yellow-600 flex flex-col items-center">
                      <Clock className="w-16 h-16 mb-4 animate-pulse" />
                      <span className="font-bold text-xl">Menunggu Pemeriksaan Guru</span>
                      <p className="text-sm text-gray-600 mt-2 max-w-xs">
                          Jawabanmu sudah terkirim. Guru akan segera memeriksa dan memberikan nilai.
                      </p>
                    </div>
                  )}
                </div>
              ) : (
                <div className="space-y-6">
                  {/* Validation Error Message */}
                  {formError && (
                    <div className="p-3 bg-red-100 text-red-700 rounded-lg flex items-center gap-2 text-sm font-bold">
                        <AlertCircle className="w-4 h-4"/> {formError}
                    </div>
                  )}
                  {submitSuccess && (
                     <div className="p-3 bg-green-100 text-green-700 rounded-lg flex items-center gap-2 text-sm font-bold">
                        <CheckCircle className="w-4 h-4"/> Berhasil terkirim!
                    </div>
                  )}

                  {/* Reflection Questions */}
                  {selectedMaterial.questions.map(q => (
                    <div key={q.id}>
                      <label className="block font-medium text-gray-800 mb-2">{q.text}</label>
                      <textarea 
                        className="w-full border border-gray-300 p-3 rounded-lg focus:ring-2 focus:ring-orange-300 outline-none transition"
                        rows={3}
                        placeholder="Tulis jawaban refleksi disini..."
                        onChange={e => setAnswers({...answers, [q.id]: e.target.value})}
                      />
                    </div>
                  ))}

                  {/* Task Submission Section */}
                  {selectedMaterial.hasTask && (
                    <div className="bg-white p-6 rounded-lg border border-gray-200 mt-6 shadow-sm">
                      <p className="font-bold text-lg text-gray-800 mb-2">Tugas: {selectedMaterial.taskDescription}</p>
                      <p className="text-sm text-gray-500 mb-4">Pilih cara pengumpulan tugas:</p>
                      
                      {/* Tabs */}
                      <div className="flex gap-2 mb-4">
                         <button 
                           onClick={() => { setTaskType('TEXT'); setTaskContent(''); }}
                           className={`flex-1 py-2 rounded-lg flex items-center justify-center gap-2 font-medium transition ${taskType === 'TEXT' ? 'bg-senja-secondary text-white shadow-md' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}
                         >
                            <Type className="w-4 h-4" /> Ketik Jawaban
                         </button>
                         <button 
                           onClick={() => { setTaskType('IMAGE'); setTaskContent(''); }}
                           className={`flex-1 py-2 rounded-lg flex items-center justify-center gap-2 font-medium transition ${taskType === 'IMAGE' ? 'bg-senja-secondary text-white shadow-md' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}
                         >
                            <ImageIcon className="w-4 h-4" /> Upload Gambar
                         </button>
                      </div>

                      {/* Input Area */}
                      <div className="min-h-[150px]">
                        {taskType === 'TEXT' ? (
                             <textarea 
                                className="w-full border p-4 rounded-lg focus:ring-2 focus:ring-senja-secondary outline-none h-40 bg-gray-50"
                                placeholder="Ketik jawaban tugasmu disini..."
                                value={taskContent}
                                onChange={e => setTaskContent(e.target.value)}
                             />
                        ) : (
                             <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 flex flex-col items-center justify-center bg-gray-50 hover:bg-gray-100 transition relative">
                                {taskContent ? (
                                    <div className="relative w-full">
                                        <img src={taskContent} alt="Preview" className="max-h-64 mx-auto rounded shadow-sm" />
                                        <button 
                                          onClick={() => setTaskContent('')}
                                          className="absolute top-2 right-2 bg-red-500 text-white p-2 rounded-full shadow-lg hover:bg-red-600"
                                        >
                                           <Trash2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                ) : (
                                    <label className="cursor-pointer w-full h-full flex flex-col items-center justify-center py-8">
                                        <Upload className="w-12 h-12 text-gray-400 mb-2" />
                                        <span className="text-gray-600 font-medium">Klik untuk upload gambar</span>
                                        <span className="text-xs text-gray-400 mt-1">Maksimal 1MB</span>
                                        <input type="file" className="hidden" accept="image/*" onChange={handleFileChange} />
                                    </label>
                                )}
                             </div>
                        )}
                      </div>
                    </div>
                  )}

                  <button 
                    onClick={handleSubmit}
                    disabled={isSubmitting || submitSuccess}
                    className={`w-full text-white py-4 rounded-xl font-bold text-lg shadow-lg transform transition active:scale-95 flex items-center justify-center ${
                        submitSuccess ? 'bg-green-600 cursor-not-allowed' : 'bg-senja-primary hover:bg-orange-600'
                    }`}
                  >
                    {isSubmitting ? <Loader2 className="w-5 h-5 animate-spin mr-2"/> : submitSuccess ? <CheckCircle className="w-5 h-5 mr-2"/> : null}
                    {submitSuccess ? 'Berhasil Dikirim!' : 'Kirim Jawaban & Tugas'}
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
        
        {/* Certificate Modal - MOVED INSIDE selectedMaterial BLOCK */}
        {showCert && (
            <div className="fixed inset-0 bg-black/80 z-[60] flex items-center justify-center p-4">
            <div className="bg-white rounded-xl w-full max-w-4xl overflow-hidden shadow-2xl animate-in zoom-in duration-300">
                <div className="bg-gray-100 p-4 flex justify-between items-center border-b">
                    <h3 className="font-bold text-gray-800">Sertifikat Digital</h3>
                    <button onClick={() => setShowCert(false)} className="text-gray-500 hover:text-red-500"><X className="w-6 h-6" /></button>
                </div>
                <div className="p-4 bg-gray-200 overflow-auto max-h-[70vh] flex justify-center">
                    <div className="w-full max-w-2xl shadow-lg">
                        <CertificateView />
                    </div>
                </div>
                <div className="p-4 border-t flex justify-end gap-3">
                    <button onClick={() => setShowCert(false)} className="px-4 py-2 text-gray-600 font-medium">Tutup</button>
                    <button onClick={handlePrintCert} className="px-6 py-2 bg-senja-primary text-white rounded-lg font-bold hover:bg-orange-600 flex items-center gap-2">
                        <Download className="w-4 h-4" /> Cetak / Unduh
                    </button>
                </div>
            </div>
            </div>
        )}
      </div>
    );
  }

  return (
    <div className="animate-in fade-in duration-500">
      <h2 className="text-2xl font-bold text-gray-800 mb-6">Bacaan Saya</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {materials.map(m => {
          const status = getStatus(m.id);
          return (
            <div key={m.id} className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition">
               <div className="h-32 bg-gray-200 flex items-center justify-center relative overflow-hidden group">
                 {m.mediaUrl ? (
                   <img src={m.mediaUrl} className="w-full h-full object-cover transition duration-500 group-hover:scale-110" alt="" />
                 ) : (
                   <span className="text-gray-400 font-bold text-2xl">SENJA</span>
                 )}
                 <div className="absolute inset-0 bg-black/10 group-hover:bg-black/0 transition"></div>
               </div>
               <div className="p-4">
                 <h3 className="font-bold text-lg mb-2 line-clamp-1">{m.title}</h3>
                 <div className="flex justify-between items-center mt-4">
                    {status === 'APPROVED' && <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded font-bold flex items-center gap-1"><CheckCircle className="w-3 h-3"/> Selesai</span>}
                    {status === 'PENDING' && <span className="text-xs bg-yellow-100 text-yellow-700 px-2 py-1 rounded font-bold flex items-center gap-1"><Clock className="w-3 h-3"/> Menunggu</span>}
                    {status === 'REJECTED' && <span className="text-xs bg-red-100 text-red-700 px-2 py-1 rounded font-bold flex items-center gap-1"><AlertCircle className="w-3 h-3"/> Perbaikan</span>}
                    {status === 'NONE' && <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">Belum Dibaca</span>}
                    
                    <button 
                      onClick={() => setSelectedMaterial(m)}
                      className="bg-senja-primary text-white text-xs font-bold px-4 py-2 rounded-full hover:bg-orange-600 transition shadow-lg shadow-orange-100 transform hover:-translate-y-1"
                    >
                      Baca
                    </button>
                 </div>
               </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};